name: GitHub-Profile-Summary-Cards

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 15 * * 0'  # 毎週月曜日の日本時間0:00に実行（UTCでは15:00に相当）
  workflow_dispatch:  # 手動実行を可能にするトリガー

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate

    steps:
      - uses: actions/checkout@v2
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.MANAGE_PROFILE }}
        with:
          USERNAME: ${{ github.repository_owner }}
