name: Update README

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # 毎日0:00に実行
  workflow_dispatch:  # 手動実行を可能にするトリガー

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate GitHub Stats
        env:
          GITHUB_TOKEN: ${{ secrets.MANAGE_PROFILE }}
        run: |
          # GitHub Stats and Trophy URLs
          LANGS_URL="https://github-readme-stats.vercel.app/api/top-langs?username=MasahitoKumada&show_icons=true&locale=ja&layout=compact&theme=chartreuse-dark&count_private=true"
          STATS_URL="https://github-readme-stats.vercel.app/api?username=MasahitoKumada&show_icons=true&locale=ja&theme=chartreuse-dark&count_private=true"
          TROPHY_URL="https://github-profile-trophy.vercel.app/?username=MasahitoKumada&theme=juicyfresh&no-bg=true"
          
          # Generate README.md
          echo "# profile" > README.md
          echo "" >> README.md
          # 統計
          echo "<a href="https://github.com/anuraghazra/github-readme-stats">" >> README.md
          echo "<img src=\"$STATS_URL\" alt=\"GitHub Stats\" width=\"310\" align="left" />" >> README.md
          echo "</a>" >> README.md
          echo "" >> README.md
          # 使用言語
          echo "<a href="https://github.com/anuraghazra/github-readme-stats">" >> README.md
          echo "<img src=\"$LANGS_URL\" alt=\"Top Languages\" width=\"310\" align="left" />" >> README.md
          echo "</a>" >> README.md
          echo "" >> README.md
          # トロフィー
          echo "<img src=\"$TROPHY_URL\" alt=\"GitHub Trophy\" />" >> README.md

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update README with latest stats" || echo "No changes to commit"
          git push
