name: Update README

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 16 * * 0'  # 毎週月曜日の日本時間1:00に実行（UTCでは16:00に相当）
  workflow_dispatch:  # 手動実行を可能にするトリガー

jobs:
  update-github-profile-summary-cards:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: generate_github-profile-summary-cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.MANAGE_PROFILE }}
        with:
          USERNAME: ${{ github.repository_owner }}

  update-readme:
    needs: update-github-profile-summary-cards
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate GitHub Stats
        env:
          GITHUB_TOKEN: ${{ secrets.MANAGE_PROFILE }}
        run: |
          # GitHub Stats and Trophy URLs
          LANGS_URL="https://github-readme-stats.vercel.app/api/top-langs?username=MasahitoKumada&show_icons=true&locale=ja&layout=compact&theme=chartreuse-dark&count_private=true"
          STATS_URL="https://github-readme-stats.vercel.app/api?username=MasahitoKumada&show_icons=true&locale=ja&theme=chartreuse-dark&count_private=true"
          TROPHY_URL="https://github-profile-trophy.vercel.app/?username=MasahitoKumada&theme=juicyfresh&no-bg=true"
          
          # Generate README.md
          echo "# profile" > README.md
          echo "" >> README.md
          # 統計
          echo "<a href="https://github.com/anuraghazra/github-readme-stats">" >> README.md
          echo "<img src=\"$STATS_URL\" alt=\"GitHub Stats\" width=\"310\" align="left" />" >> README.md
          echo "</a>" >> README.md
          echo "" >> README.md
          # 使用言語
          echo "<a href="https://github.com/anuraghazra/github-readme-stats">" >> README.md
          echo "<img src=\"$LANGS_URL\" alt=\"Top Languages\" width=\"310\" align="left" />" >> README.md
          echo "</a>" >> README.md
          echo "" >> README.md
          # トロフィー
          echo "<img src=\"$TROPHY_URL\" alt=\"GitHub Trophy\" />" >> README.md
          echo "" >> README.md
          # profile-summary-cards(https://github.com/vn7n24fzkq/github-profile-summary-cards?tab=readme-ov-file) 
          echo "[![](https://raw.githubusercontent.com/MasahitoKumada/MasahitoKumada/main/profile-summary-card-output/2077/0-profile-details.svg)](https://github.com/vn7n24fzkq/github-profile-summary-cards)" >> README.md
          echo "[![](https://raw.githubusercontent.com/MasahitoKumada/MasahitoKumada/main/profile-summary-card-output/2077/1-repos-per-language.svg)](https://github.com/vn7n24fzkq/github-profile-summary-cards) [![](https://raw.githubusercontent.com/MasahitoKumada/MasahitoKumada/main/profile-summary-card-output/2077/2-most-commit-language.svg)](https://github.com/vn7n24fzkq/github-profile-summary-cards)" >> README.md
          echo "[![](https://raw.githubusercontent.com/MasahitoKumada/MasahitoKumada/main/profile-summary-card-output/2077/3-stats.svg)](https://github.com/vn7n24fzkq/github-profile-summary-cards) [![](https://raw.githubusercontent.com/MasahitoKumada/MasahitoKumada/main/profile-summary-card-output/2077/4-productive-time.svg)](https://github.com/vn7n24fzkq/github-profile-summary-cards)" >> README.md

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update README with latest stats" || echo "No changes to commit"
          git pull --rebase origin main
          git push
